development:
  adapter: sqlite3
  encoding: unicode
  database: 'vidi_development.db'
#  pool: 2
  # username: your_username
  # password: your_password

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: <%= ENV['PG_USER']%>
  password: <%= ENV['PG_PASS']%>
  database: 'DATABASE_URL'
